image: "rocker/verse:4.0.3"

stages:
 - download
 - site

nvsc:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "nvsc"
    script:
      - R -e "install.packages('gert')"
      - R -e "try(source('R/download_nvsc.R'))"
      - R -e "source('R/makefile_samrc.R')"

sam:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "sam"
    script:
      - R -e "install.packages('gert')"
      - R -e "try(source('R/download_sam.R'))"
      - R -e "source('R/makefile_samrc.R')"


datagov:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "datagov"
    script:
      - R -e "install.packages('gert')"
      - R -e "source('R/makefile_datagov.R')"
    artifacts:
      paths:
        - data
      expire_in: 1 day


update:
    stage: site
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "datagov"
    script:
      - R -e "install.packages(c('gert','COVID19','dygraphs','xts', 'gridExtra','distill','EpiEstim','flexdashboard'))"
      - rm README.md
      - R -e "source('R/makefile_site.R')"