image: "rocker/verse:4.0.3"

stages:
 - download
 - site

osp:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "osp"
    script:
      - R -e "install.packages(c('gert','zoo'))"
      - R -e "source('R/makefile_osp_live.R')"

datagov:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "datagov"
    script:
      - R -e "install.packages('gert')"
      - R -e "source('R/makefile_datagov.R')"
    artifacts:
      paths:
        - data
      expire_in: 1 day


update:
    stage: site
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "datagov"
    script:
      - R -e "install.packages(c('gert','COVID19','dygraphs','xts', 'gridExtra','distill','EpiEstim','flexdashboard'))"
      - rm README.md
      - R -e "source('R/makefile_site.R')"