image: "rocker/verse:latest"

stages:
 - download
 - site

nvsc:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "nvsc"
    script:
      - R -e "install.packages('gert')"
      - R -e "source('R/makefile_samrc.R')"

datagov:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "datagov"
    script:
      - R -e "install.packages('gert')"
      - R -e "source('R/makefile_datagov.R')"

update:
    stage: site
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "datagov"
    script:
      - R -e "install.packages(c('gert','COVID19','dygraphs','xts', 'gridExtra','distill','EpiEstim','flexdashboard'))"
      - R -e "source('R/makefile_site.R')"