image: "rocker/verse:latest"

nvsc:
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "nvsc"
    script:
      - R -e "install.packages('gert')"
      - R -e "source('R/makefile_samrc.R')"
