image: "rocker/verse:4.0.3"

stages:
 - download
 - site
 - regions

osp:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "osp"
    script:
      - R -e "install.packages(c('gert','zoo'))"
      - R -e "source('R/makefile_osp_live.R')"
    artifacts:
      paths:
        - data
      expire_in: 1 day


datagov:
    stage: download
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "datagov"
    script:
      - R -e "install.packages(c('gert', 'zoo'))"
      - R -e "source('R/makefile_osp_live.R')"
      - R -e "source('R/makefile_datagov.R')"
    artifacts:
      paths:
        - data
      expire_in: 1 day


update_site:
    stage: site
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "partial"
    script:
      - R -e "install.packages(c('gert','COVID19','dygraphs','xts', 'gridExtra','distill','EpiEstim','flexdashboard'))"
      - rm README.md
      - R -e "source('R/makefile_part_site.R')"
    artifacts:
      paths:
        - docs
      expire_in: 1 day


update:
    stage: regions
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "datagov"
    script:
      - R -e "install.packages(c('gert','COVID19','dygraphs','xts', 'gridExtra','distill','EpiEstim','flexdashboard'))"
      - rm README.md
      - R -e "source('R/makefile_site.R')"
      - git push github
    artifacts:
      paths:
        - docs
      expire_in: 1 day

update_osp:
    stage: regions
    only:
      refs :
        - master
        - schedules
      variables:
        - $SOURCE == "osp"
    script:
      - R -e "install.packages(c('gert','COVID19','dygraphs','xts', 'gridExtra','distill','EpiEstim','flexdashboard'))"
      - rm README.md
      - R -e "source('R/makefile_site.R')"
      - git push github
    artifacts:
      paths:
        - docs
      expire_in: 1 day
